# 工作流程名稱
name: Deploy
# 觸發時機：當main分支被push的時候
on:
  push:
    branches:
      - main
# 處理的工作：底下包含Build和Deploy兩階段
jobs:
  build:
    name: Build
    # 在ubuntu-latest虛擬環境上執行
    runs-on: ubuntu-latest
    # 定義工作步驟
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
  # 第二階段的工作
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          # 這裡的金鑰使用公開金鑰，須小心安全性的問題
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
